apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    environment: dev
spec:
  containers:
    - name: pyton-app
      image: udaydevmac/python-app:latest
      ports:
        - containerPort: 5000