apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  terminationGracePeriodSeconds: 40
  restartPolicy: OnFailure
  volumes:
    - name: temp-vol
      emptyDir:
        sizeLimit: 10Mi  
  containers:
    - name: busybox-1
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh","-c", sleep "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: /data
          name: temp-vol
    - name: busybox-2
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh","-c", sleep "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: /data
          name: temp-vol
    
      