apiVersion: v1
kind: Pod
metadata:
  name: hosthpath-demo
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh","-c","cat /data && sleep 3600"]
    resources:
      requests:
        cpu: "125m"
        memory: "100Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: hostpath-vol
        mountPath: /data
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /tmp/hostfile
        type: FileOrCreate
