apiVersion: v1
kind: Pod
metadata:
  name: pod-aws-vol-demo
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: aws-vol
        mountPath: "/usr/share/nginx/html"
  volumes:
    - name: aws-vol
      persistentVolumeClaim:
        claimName: pvc-aws-demo
