apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aws-demo
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: pv-aws-demo
