apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  voluneName: pv-demo
