apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual
  namespace: dev-ns
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
  nodeName: test-worker
