apiVersion: v1
kind: Pod
metadata:
  name: rp-demo
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: nginx-conatiner
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
