apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  tier: frontend
spec:
  initContainers:
    - name: curl
      image: curlimages/curl:7.85.0
      command:
      - sh
      - -c
      - |
        echo "Waiting for the service to be available..."
        sleep 25
        until nslookup nginx-svc.default.svc.cluster.local; do
          echo "Service not available yet. Retrying in 5 seconds..."
          sleep 5
        done
        echo "Service is now available!"
  containers:
  - name: main-app
    image: nginx


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: main-app
  ports:
  - port: 80
    targetPort: 80
