apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: APP
        valueFrom:
          configMapKeyRef:
            name: cm1-demo
            key: APP
      - name: PROD
        valueFrom:
          configMapKeyRef:
            name: cm1-demo
            key: ENV
    ports:
      - containerPort: 80
