apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: myapp
          image: udaydevmac/pyton-app:latest
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      type: frontend